In [1]:
import numpy as np
#step-1
data = np.array([
    ["C001", 5, "Excellent service and friendly staff"],
    ["C002", 4, "Good product selection but long wait time"],
    ["C003", 3, "Average experience, checkout was slow"],
    ["C004", 5, "Loved the discounts! Will shop again"],
    ["C005", 2, "Poor customer support, not satisfied"],
    ["C006", 4, "Good quality but a bit expensive"],
    ["C007", 1, "Terrible experience, rude staff"],
    ["C008", 5, "Amazing deals and fast service"],
])


In [2]:
print(data)

[['C001' '5' 'Excellent service and friendly staff']
 ['C002' '4' 'Good product selection but long wait time']
 ['C003' '3' 'Average experience, checkout was slow']
 ['C004' '5' 'Loved the discounts! Will shop again']
 ['C005' '2' 'Poor customer support, not satisfied']
 ['C006' '4' 'Good quality but a bit expensive']
 ['C007' '1' 'Terrible experience, rude staff']
 ['C008' '5' 'Amazing deals and fast service']]


In [3]:
#step-2 convert ratings into int
ratings=data[:,1].astype(int)
total_ratings=len(ratings)
print('Total feedback ratings:',total_ratings)

Total feedback ratings: 8


In [4]:
print(ratings)

[5 4 3 5 2 4 1 5]


In [5]:
# step-3-> perform statistical analysis-> mean 
# find avg rating
avg_rating=np.mean(ratings)
print('avg rating:',avg_rating)

avg rating: 3.625


In [6]:
# calculating highest rating
high_rating=np.max(ratings)
print('high_rating:-',high_rating)

high_rating:- 5


In [7]:
# calculating lowest rating
low_rating=np.min(ratings)
print('low_rating:-',low_rating)

low_rating:- 1


In [8]:
print(ratings)

[5 4 3 5 2 4 1 5]


In [18]:
# #calculate u nique ratings
# unique_rating=np.unique(ratings)
# print(unique_rating)

In [26]:
unique_ratings,rating_counts=np.unique(ratings,return_counts=True)
print(unique_ratings)
print(rating_counts)

[1 2 3 4 5]
[1 1 1 2 3]


In [23]:
print(data)

[['C001' '5' 'Excellent service and friendly staff']
 ['C002' '4' 'Good product selection but long wait time']
 ['C003' '3' 'Average experience, checkout was slow']
 ['C004' '5' 'Loved the discounts! Will shop again']
 ['C005' '2' 'Poor customer support, not satisfied']
 ['C006' '4' 'Good quality but a bit expensive']
 ['C007' '1' 'Terrible experience, rude staff']
 ['C008' '5' 'Amazing deals and fast service']]


In [27]:
# step4-extract text feedback for qualitative insights
feedback_comments=data[:,2]
print('Display customer feedbacks insights:-')
print()
print('***rating distribution***')
print()
for rating,count in zip(unique_ratings,rating_counts):
    print(f"Rating {rating}:{count} customers")

Display customer feedbacks insights:-

***rating distribution***

Rating 1:1 customers
Rating 2:1 customers
Rating 3:1 customers
Rating 4:2 customers
Rating 5:3 customers
