In [1]:
import numpy as np

In [2]:
import time

In [8]:
lst=list(range(100000))
arr=np.arange(100000)
start=time.time()
sum(lst)
print('List time:-',time.time()-start)
start=time.time()
np.sum(arr)
print('Numpy Time:-',time.time()-start)

List time:- 0.0010831356048583984
Numpy Time:- 0.00032210350036621094


In [10]:
# creating arrays

In [11]:
#1-D array
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [12]:
# 2-D array
arr=np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(arr+5)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [14]:
print(arr*5)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [19]:
#array of zeros
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
#array of ones
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#start , end, step
range_array=np.arange(1,11,2)
print(range_array)

[1 3 5 7 9]


In [24]:
arr_1=np.array([1,2,3])
arr_2=np.array([1,2,3])
print(arr_1+arr_2)
print(arr_1*arr_2)


[2 4 6]
[1 4 9]


In [26]:
#indexing , slicing, reshaping
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [30]:
#slicing
print('printing first row:-',arr[0,:])
print('printing second row:-',arr[1,:])
print('printing third row:-',arr[2,:])

printing first row:- [1 2 3]
printing second row:- [4 5 6]
printing third row:- [7 8 9]


In [33]:
print('print column',arr[:,0])
print('print column',arr[:,1])
print('print column',arr[:,2])
print('print column',arr[:,-1])

print column [1 4 7]
print column [2 5 8]
print column [3 6 9]
print column [3 6 9]


In [34]:
# rehaping- row,column
arr=np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
# useful functions of numpy
arr=np.array([1,2,3,4,5])
print('mean of arr',np.mean(arr))
print('median of arr',np.median(arr))
print('max of arr',np.max(arr))
print('min of arr',np.min(arr))
print('standard deviation:',np.std(arr))


mean of arr 3.0
median of arr 3.0
max of arr 5
min of arr 1
standard deviation: 1.4142135623730951


In [40]:
#linespace
lin=np.linspace(0,1,5)
print('linespace 0 to 1:',lin)

linespace 0 to 1: [0.   0.25 0.5  0.75 1.  ]


In [41]:
#random-> 2 row , 3 column with random elements between 1 to 10
arr=np.random.randint(1,10,(2,3))
print(arr)

[[7 1 8]
 [4 3 7]]


In [43]:
arr=np.arange(1,26,1).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [49]:
arr=np.arange(25).reshape(5,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [51]:
arr=np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [52]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# if axis=0 then row
# if axis=1then column

In [54]:
# calculating the sum of each row
row_sum=np.sum(arr,axis=1)
print('row wise sum:-',row_sum)

row wise sum:- [ 15  40  65  90 115]


In [56]:
# calculating the sum of each row
col_sum=np.sum(arr,axis=0)
print('col wise sum:-',col_sum)

col wise sum:- [55 60 65 70 75]
